name: gknow
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.3.1+1
  path: ^1.7.0

  shared_preferences: ^0.5.12+4
  workmanager: ^0.2.3
  path_provider: ^1.6.27
  flutter_local_notifications: ^3.0.2
  http: ^0.12.0+2
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  connectivity: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/profile.png
  uses-material-design: true
